# Makefile
TARGET	= user_test
CC	= gcc
NVCC	= nvcc -arch sm_20 -cubin
LIBS	= -lcuda
CFLAGS	= -I /usr/local/cuda/include

all:
	$(NVCC) -o idle_gpu.cubin idle_gpu.cu
	gcc -o $(TARGET) $(CFLAGS) main.c idle.c $(LIBS)

clean:
	rm -f $(TARGET) *.cubin ./*~
